version: "3.3"

services:
  pintel_postgres:
    container_name: pintel_postgres
    image: "postgres:14"
    env_file:
      - .env
    restart: always
    networks:
      - postgres-db-network
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "5437:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  postgres-db-network:
    driver: bridge