server:
  port: 8083

telegram:
  api-url: https://api.telegram.org/
  webhook-path: https://90da-178-66-130-249.ngrok-free.app
  bot-name: PinTelBot
  bot-token: 6940539957:AAFTK2PcKutWgb5QCD7jzXlnCmfRk4rO14Y

spring:
  datasource:
    username: ${POSTGRES_USER:postgres1}
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5437/pintel}
    password: ${POSTGRES_PASSWORD:postgres1}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: full
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
feign:
  okhttp:
    enabled: true

pinterest:
  link: "https://serpapi.com/search.json"
  api-key: "dbc198ea68d297a5a89ffc8e145d59eb5119588c458a079a6ac979ab3ed7d472"
  engine: "yandex_images"

watermark:
  url:

meaning-tags:
  url: http://192.168.0.19:8000

color-tags:
  url: http://1


